version: "3.7"
services:
  db:
    image: postgres
    container_name: project_name_db
    ports:
        - "5432:5432"
    env_file:
        - .development
  web:
    build: .
    image: project_name
    container_name: project_name_web
    depends_on:
        - db
    volumes:
        - .:/project_name
    ports:
        - "8000:8000"
    env_file:
        - .development

